//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewCommonDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Effort
    {
        public int effort_id { get; set; }
        public Nullable<int> assign_task_id { get; set; }
        public Nullable<int> shift_id { get; set; }
        public int hours_worked { get; set; }
        public Nullable<System.DateTime> submitted_date { get; set; }
        public string status { get; set; }
    
        public virtual Assign_Task Assign_Task { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
